from enum import Enum

CEA608_FORMAT = "cea608"
CEA708_FORMAT = "cea708"


class CaptionFormat(str, Enum):
    CEA608 = CEA608_FORMAT
    CEA708 = CEA708_FORMAT


TEMP_OUTPUT_DIR = "/tmp/caption_output"

UNKNOWN_DEBUG_LEVEL = "UNKNOWN_DEBUG_LEVEL"
VERBOSE = "VERBOSE"
INFO = "INFO"
WARN = "WARN"
ERROR = "ERROR"
FATAL = "FATAL"
ASSERT = "ASSERT"
DEBUG_LEVELS = [
    UNKNOWN_DEBUG_LEVEL,
    VERBOSE,
    INFO,
    WARN,
    ERROR,
    FATAL,
    ASSERT,
]


class DebugLevels(str, Enum):
    UNKNOWN_DEBUG_LEVEL = UNKNOWN_DEBUG_LEVEL
    VERBOSE = VERBOSE
    INFO = INFO
    WARN = WARN
    ERROR = ERROR
    FATAL = FATAL
    ASSERT = ASSERT
